M48
; DRILL file {KiCad (7.0.0)} date Tue Feb 28 10:19:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-28T10:19:30+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.8425Y-2.8937
X4.8425Y-4.9606
X6.9291Y-2.8937
X6.9291Y-4.9606
T0
M30
